# Multi os support is currenly in beta and not enabled by default
# os:
#   - linux
#   - osx

language: python

python:
  - "2.7"
  # - "3.0" # Depends on the support of Python 3 from twisted

install:
  - "pip install --upgrade pip"
  - "pip install virtualenv"
  - npm install -g gulp
  - npm install -g bower

script:
  - "install/install.py"

after_script:
  - "workdir/bin/activate && trial squirrel"
  - "workdir/bin/activate && trial squirrel_integration_tests"
