# Multi os support is currenly in beta and not enabled by default
# os:
#   - linux
#   - osx

language: python


python:
  - "2.7"
  - "3.4"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq --fix-missing postgresql-server-dev-all"
  - "pip install --upgrade pip"
  - "pip install virtualenv"
  - "npm install -g gulp"
  - "npm install -g bower"

script:
  - "install/install.py install:all"
  - "source workdir/bin/activate && trial squirrel"
  - "source workdir/bin/activate && trial squirrel_integration_tests"
  - "install/uninstall.py"
