# Note
# relative paths in this file should use the relative path from the "backend" subdirectory
frontend:
    root_path: ../frontend/dist/
    doc_path: ../doc/build/html/
    port: 8080
    logging_conf_path: ./squirrel/logging.conf

backend:
    db:
        workdir: ../workdir/
        url: sqlite:///../workdir/db.sqlite

plugins:
    default_path: ../plugins/
