# Note
# relative paths in this file should use the relative path from the "backend" subdirectory
frontend:
    root_path: ../frontend/dist/
    doc_path: ../doc/build/html/
    dev_port: 8080
    prod_port: 80
    logging_conf_path: ./squirrel/logging.conf

backend:
    db:
        workdir: ../workdir/
        url: sqlite:///../workdir/db.sqlite

plugins:
    default_path: ../plugins/

crawlers:
    'RefreshGoogleFinance':
        description: |
            Refresh the list of stocks provided by Google Finance.

        plugin_name: GoogleFinance
        refresh_list:
            manual: enabled
        refresh:
            exchanges:
                wanted: all
                group_by: 60
            stocks:
                'NASDAQ':
                    - "AAPL"
                    - "GOOG"

marketing:
    general:
    country:
        fr:
            homepage_accounts:
                -
                    name: "Assurance Vie"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "Compte Titre Ordinaire"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "PEA, PEA-PME"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "PERP, PERCO, Article 83"
                    icon_type: "fa fa-envelope fa-3x"
                -
                    name: "Compte Courant"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "Contrat de Capitalisation"
                    icon_type: "fa fa-envelope fa-3x"
        us:
            homepage_accounts:
                -
                    name: "Individual Account"
                    icon_type: "fa fa-user fa-3x"
                -
                    name: "Joint Account"
                    icon_type: "fa fa-users fa-3x"
                -
                    name: "IRA"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "401(1k)"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "Stock Account"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "Other Type"
                    icon_type: "fa fa-envelope fa-3x"
        en:
            homepage_accounts:
                -
                    name: "Individual Account"
                    icon_type: "fa fa-user fa-3x"
                -
                    name: "Joint Account"
                    icon_type: "fa fa-users fa-3x"
                -
                    name: "IRA"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "401(1k)"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "Stock Account"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "Other Type"
                    icon_type: "fa fa-envelope fa-3x"
