# Note
# relative paths in this file should use the relative path from the "backend" subdirectory
flavour:
    config_file: 'config-{flavour}.yaml'

logging:
    use_split_formatter: true
    use_color_formatter: true
    config_file: ./squirrel/logging.conf

frontend:
    root_path: ../frontend/dist/
    doc_path: ../doc/build/html/
    html5mode: true

backend:
    serve: false
    db:
        workdir: ../workdir/
        url: sqlite:///../workdir/db.sqlite

plugins:
    default_path: ../plugins/

crawlers:
    'RefreshGoogleFinance':
        description: |
            Refresh the list of stocks provided by Google Finance.

        plugin_name: GoogleFinance
        refresh_list:
            manual: enabled
        refresh:
            exchanges:
                wanted: all
                group_by: 60
            stocks:
                'NASDAQ':
                    - "AAPL"
                    - "GOOG"

marketing:
    general:
    country:
        fr:
            homepage_accounts:
                -
                    name: "Assurance Vie"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "Compte Titre Ordinaire"
                    icon_type: "fa fa-line-chart fa-3x"
                -
                    name: "PEA, PEA-PME"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "PERP, PERCO, Article 83"
                    icon_type: "fa fa-envelope fa-3x"
                -
                    name: "Compte Courant"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "CFD"
                    icon_type: "fa fa-heartbeat fa-3x"
        us:
            homepage_accounts:
                -
                    name: "Individual Account"
                    icon_type: "fa fa-user fa-3x"
                -
                    name: "Joint Account"
                    icon_type: "fa fa-users fa-3x"
                -
                    name: "IRA"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "401(1k)"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "Stock Account"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "Other Type"
                    icon_type: "fa fa-envelope fa-3x"
        en:
            homepage_accounts:
                -
                    name: "Individual Account"
                    icon_type: "fa fa-user fa-3x"
                -
                    name: "Joint Account"
                    icon_type: "fa fa-users fa-3x"
                -
                    name: "IRA"
                    icon_type: "fa fa-umbrella fa-3x"
                -
                    name: "401(1k)"
                    icon_type: "fa fa-book fa-3x"
                -
                    name: "Stock Account"
                    icon_type: "fa fa-bank fa-3x"
                -
                    name: "Other Type"
                    icon_type: "fa fa-envelope fa-3x"

settings:
    country:
        fr:
            # Use special HTML character!
            'Assurance Vie':
                - 'Assurance Vie (AV)'
                - 'Contrat de Capitalisation'
                - 'Tontine'
                - "Plan d'&Eacute;pargne Entreprise (PEE)"
                - "Plan d'&Eacute;pargne pour la Retraite Collectif (PERCO)"
                - "Plan d'&Eacute;pargne Retraite Populaire (PERP)"
                - 'Article 83 (A83)'
                - 'Compl&eacute;mentaire Retraite des Hospitaliers (CRH)'
                - 'Pr&eacute;fon'
                - 'Contrats Madelin'
            "Actions en Direct (Bourse)":
                - "Plan d'&Eacute;pargne Action (PEA)"
                - "Plan d'&Eacute;pargne en Actions destin&eacute; au financement des PME et ETI (PEA-PME)"
                - 'Compte Titre Ordinaire (CTO)'
                - 'Stock Options'
            'Immobilier':
                - 'R&eacute;sidence Principale'
                - 'Borloo'
                - 'Cenci Bouvard'
                - 'Duflot'
                - 'Locatif Ancien'
                - 'Immobilier Nu propri&eacute;t&eacute;'
                - 'Immobilier Usufruit'
                - 'Immobilier Viag&eacute;'
                - 'Immobilier &agrave; l &eacute;tranger'
                - 'Investissement Hotelier'
                - 'LMNP'
                - 'LMP'
                - 'Malraux'
                - 'Monument Historique'
                - 'OCPI'
                - 'Part de Soci&eacute;t&eacute; Civile de Placement Immobilier (SCPI)'
                - 'SCPI en nu propri&eacute;t&eacute; Parking'
                - 'Pinel'
                - 'Scellier'
                - 'Socit&eacute; Civile Immobili&egrave;re (SCI)'
                - 'Robien'
            "Placement Alternatifs":
                - "Fonds d'Investissement de Proximit&eacute; (FIP)"
                - "Fonds Commun de Placement dans l'Innovation (FCPI)"
                - 'Bijoux'
                - 'Chevaux de course'
                - 'Bois et Foret (GFF)'
                - 'Investissement en direct dans une PME'
                - 'Meuble de collection'
                - 'Or/M&eacute;taux pr&eacute;cieux'
                - 'Sofica'
                - "Tableaux et Oeuvre d'Art"
                - 'Terre Agricole (GFA)'
                - 'Vache laiti&egrave;re'
                - 'Vigne (GFV)'
                - 'Vin'
                - 'Voiture et Bateau'
            "Biens professionnels":
                - 'Parts d&eacute;tenues par les salari&eacute;s et mandataires sociaux'
                - 'Valeurs mobili&egrave;res et biens mat&eacute;riels - Biens professionnels'
            "Comptes Sp&eacute;culatifs":
                - 'CFD (Forex ou Indices)'
                - 'Autre Compte Speculatif (Futures, Options,...)'
            "Autre Type de Portefeuille":
                - "Type de portefeuille Personnalis&eacute; (Autre)"

