frontend:
    port: $PORT

logging:
    use_split_formatter: false
    config_file: ./squirrel/logging-heroku.conf

backend:
    serve: true
    db:
        workdir: ../log/
        url: $DATABASE_URL
