logging:
    use_split_formatter: true
    config_file: ./squirrel/logging.conf

frontend:
    port: 80

backend:
    serve: true
    db:
        workdir: ../workdir/
        url: sqlite:///../workdir/db.sqlite
